[workspace]
authors = []
channels = ["conda-forge"]
name = "supplement-2025-microstructure-evaluation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
esys-escript = "==5.10"
packaging = "==24.2"

[pypi-dependencies]
mammos = "==0.3.0"
pandas = "==2.2.3"
